### ISSUE TITLE
Namespace arguments broken in spack.repo API

### ISSUE THREAD

**Issue by alalazo** [spack/spack#11159]
While coding towards #11158 I tried to use a custom namespace for the temporary repository being used. This caused strange errors, as for repositories that are not in the `spack.pkg` namespace directives won't be executed on their packages.

### Steps to reproduce the issue

```console
$ spack-python
Spack version 0.12.1
Python 2.7.15rc1, Linux x86_64
>>> import spack.repo
>>> import spack.spec
# Any repository path will be fine below
>>> repo = spack.repo.Repo('/tmp/tmp4yoo27fk', namespace='custom')
>>> spack.repo.path.put_first(repo)
# Choose a package in the custom repo
>>> s = spack.spec.Spec('concretizationroot')
>>> s.concretize()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1909, in concretize
    user_spec_deps=user_spec_deps),
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2322, in normalize
    self.validate_or_raise()
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2374, in validate_or_raise
    spack.repo.get(spec.fullname)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 1198, in get
    return path.get(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 85, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 644, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 85, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 906, in get
    raise FailedConstructorError(spec.fullname, *sys.exc_info())
FailedConstructorError: Class constructor failed for package 'concretizationroot'.
    
Caused by:
AttributeError: 'Concretizationroot' object has no attribute 'versions'
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 897, in get
    return package_class(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/package.py", line 488, in __init__
    for v in self.versions:
```

### Additional information

This bug apparently was introduced in 39c9bbfbb which added this check:

https://github.com/spack/spack/blob/b2611c80862628046556c73e1e9da6ec69060428/lib/spack/spack/directives.py#L102-L104

to `DirectivesMeta`, which results in directives being executed only if the namespace of a repository is the default one. As a solution we could either relax this check, or simplify the repository interface by removing its optional `namespace` argument.

**Comment by scheibelp** [comment]
> This bug apparently was introduced in 39c9bbf which added this check:

39c9bbf didn't add that check: it changed how it was done. That being said it is definitely the case that namespaces weren't being handled properly.
