### PR TITLE
silo: depends on hdf5@:1.10.999

### PR DESCRIPTION
**Pull request by eschnett**
Silo does not build with HDF5 1.12.

### CODE REVIEW

**Comment by sethrj** [comment]
@eschnett The changes look good, but could you please post the relevant part of the error message for posterity? (I can't count the number of times I've worked around a build failure by googling the error message and hitting Spack or another issue page.)

@markcmiller86 Are you aware of this HDF5 incompatibility?

**Comment by sethrj** [comment]
@eschnett The changes look good, but could you please post the relevant part of the error message for posterity? (I can't count the number of times I've worked around a build failure by googling the error message and hitting Spack or another issue page.)

@markcmiller86 Are you aware of this HDF5 incompatibility?

**Comment by eschnett** [comment]
The relevant error messages are:
```
In file included from /Users/eschnett/src/spack-develop/opt/spack/darwin-catalin
a-skylake/gcc-9.3.0-spack/hdf5-1.12.0-gyy5rpxymia57q4rypshrbxx3vk2av7z/include/H
5public.h:32,
                 from /Users/eschnett/src/spack-develop/opt/spack/darwin-catalin
a-skylake/gcc-9.3.0-spack/hdf5-1.12.0-gyy5rpxymia57q4rypshrbxx3vk2av7z/include/h
df5.h:22,
                 from silo_hdf5_private.h:71,
                 from silo_hdf5.c:72:
silo_hdf5.c: In function 'db_hdf5_SortObjectsByOffset':
/Users/eschnett/src/spack-develop/opt/spack/darwin-catalina-skylake/gcc-9.3.0-spack/hdf5-1.12.0-gyy5rpxymia57q4rypshrbxx3vk2av7z/include/H5version.h:746:23: error: too few arguments to function 'H5Oget_info3'
  746 |   #define H5Oget_info H5Oget_info3
      |                       ^~~~~~~~~~~~
silo_hdf5.c:15763:18: note: in expansion of macro 'H5Oget_info'
15763 |                  H5Oget_info(oid, &oinfo)<0 ||
      |                  ^~~~~~~~~~~
In file included from /Users/eschnett/src/spack-develop/opt/spack/darwin-catalina-skylake/gcc-9.3.0-spack/hdf5-1.12.0-gyy5rpxymia57q4rypshrbxx3vk2av7z/include/H5Apublic.h:22,
                 from /Users/eschnett/src/spack-develop/opt/spack/darwin-catalina-skylake/gcc-9.3.0-spack/hdf5-1.12.0-gyy5rpxymia57q4rypshrbxx3vk2av7z/include/hdf5.h:23,
                 from silo_hdf5_private.h:71,
                 from silo_hdf5.c:72:
/Users/eschnett/src/spack-develop/opt/spack/darwin-catalina-skylake/gcc-9.3.0-spack/hdf5-1.12.0-gyy5rpxymia57q4rypshrbxx3vk2av7z/include/H5Opublic.h:187:15: note: declared here
  187 | H5_DLL herr_t H5Oget_info3(hid_t loc_id, H5O_info2_t *oinfo, unsigned fields);
      |               ^~~~~~~~~~~~
silo_hdf5.c:15767:38: error: 'H5O_info2_t' {aka 'struct H5O_info2_t'} has no member named 'addr'
15767 |                 iop[i].offset = oinfo.addr;
      |                                      ^
```

**Comment by sethrj** [comment]
@alalazo This is ready for merge, thanks!
