### PR TITLE
unifyfs: add patch to fix #15292

### LINKED ISSUE #15292: unifyfs fails to build, unknown type 'MPI_Fint'
Package `unifyfs` fails to build on Ubuntu 18.04, x86_64 with Spack develop (e3b357ad87). The full spack-build-log is attached, but the error is shown below. I've tried with both `mpich` and `openmpi` -- same error either way.

Full build log: [unifyfs-build-out.txt](https://github.com/spack/spack/files/4276893/unifyfs-build-out.txt)

**Error:**
```
make[3]: Entering directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build/client/src'
  CC       libunifyfs_la-margo_client.lo
  CC       libunifyfs_la-unifyfs.lo
  CC       libunifyfs_la-unifyfs-dirops.lo
  CC       libunifyfs_la-unifyfs-fixed.lo
  CC       libunifyfs_la-unifyfs-stack.lo
  CC       libunifyfs_la-unifyfs-stdio.lo
  CC       libunifyfs_la-unifyfs-sysio.lo
  CC       libunifyfs_la-pmpi_wrappers.lo
In file included from /tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/client/src/pmpi_wrappers.c:15:0:
/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/client/src/pmpi_wrappers.h:21:16: error: unknown type name 'MPI_Fint'
 void mpi_init_(MPI_Fint* ierr);
                ^~~~~~~~
/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/client/src/pmpi_wrappers.h:26:20: error: unknown type name 'MPI_Fint'
 void mpi_finalize_(MPI_Fint* ierr);
                    ^~~~~~~~
Makefile:646: recipe for target 'libunifyfs_la-pmpi_wrappers.lo' failed
make[3]: *** [libunifyfs_la-pmpi_wrappers.lo] Error 1
make[3]: Leaving directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build/client/src'
Makefile:460: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build/client'
Makefile:490: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build'
Makefile:400: recipe for target 'all' failed
make: *** [all] Error 2
```

@CamStan

### PR DESCRIPTION
**Pull request by CamStan**
UnifyFS had a bug with the `--enable-mpi-mount` config option, which corresponds to the `auto-mount` variant. This bug was fixed in the UnifyFS dev branch, however remains broken for the 0.9.0 version.

This adds a patch to the `unifyfs` package to fix the `auto-mount` variant when installing with version 0.9.0.

**Update:** the following paragraph is no longer valid.

This also removes the `openssl` dependency as `unifyfs` does not directly depend on it. This was said to be a non-explicit dependency in #15258, but I have been unable to duplicate this. However, if it is needed, it is likely a non-explicit dependency of one of unifyfs's dependencies and should be added there.

Fixes: #15292

### CODE REVIEW

**Comment by CamStan** [comment]
@eugeneswalker, if you could show me how to reproduce the issue of `unifyfs` needing `openssl`, we can get that addressed.

**Comment by eugeneswalker** [comment]
> @eugeneswalker, if you could show me how to reproduce the issue of `unifyfs` needing `openssl`, we can get that addressed.

Pull in `spack/develop` in Docker image `spack/ubuntu-bionic`. Right now unifyfs has a depends_on('openssl') -- you should remove that:

```
$> spack edit unifyfs
... remove the line w/ depends_on('openssl') 
```

and then try installing unifyfs
```
$> spack install unifyfs
```

The configure phase fails with this error:
```
...
checking openssl/md5.h usability... no
checking openssl/md5.h presence... no
checking for openssl/md5.h... no
configure: error: in `/tmp/root/spack-stage/spack-stage-unifyfs-0.9.0-wnh5bnho5zrk4ucrbw2uz2yum5xeeql6/spack-src/spack-build':
configure: error: 
        *** openssl/md5.h missing, openssl-devel package required
See `config.log' for more details
```

therefor the spack install won't proceed.

@CamStan

**Comment by CamStan** [comment]
@eugeneswalker, oh wow, yup, thank you. I put `openssl` back in (just moved where in the package it was). 

@alalazo, This should be ready now.
