### PR TITLE
Provide a patch to allow hdf5@1.10.1 to build with intel/18.0.1.

### PR DESCRIPTION
**Pull request by KineticTheory**
This is known issue.  See
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/747951.

Without this patch, hdf5 fails to build with Intel 18 due to the error:

```
    PPFC     H5f90global.lo
libtool: compile:
    /usr/projects/hpcsoft/toss3/snow/openmpi/2.1.2-intel-18.0.1/bin/mpif90
    -I. -I../../src -O3 -I../../src -I../../fortran/src -fPIC -c H5f90global.F90
    -fPIC -o .libs/H5f90global.o
/yellow/usr/projects/user_contrib/spack.20170926/lib/spack/env/intel/ifort: line
    358:
    /yellow/users/kellyt/spack-cc-hdf5@1.10.1%intel@18.0.1+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe
    arch=linux-rhel7-x86_64 /v3lut6o.in.log: No such file or directory
/yellow/usr/projects/user_contrib/spack.20170926/lib/spack/env/intel/ifort: line
    359:
    /yellow/users/kellyt/spack-cc-hdf5@1.10.1%intel@18.0.1+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe
    arch=linux-rhel7-x86_64 /v3lut6o.out.log: No such file or directory
H5f90global.F90(145): error #7615: Multiple objects from the same EQUIVALENCE
    set may not appear in a COMMON block.   [H5T_NATIVE_INTEGER_KIND]
  EQUIVALENCE (predef_types(2), H5T_NATIVE_INTEGER_KIND(2))
--------------------------------^
H5f90global.F90(146): error #7615: Multiple objects from the same EQUIVALENCE
    set may not appear in a COMMON block.   [H5T_NATIVE_INTEGER_KIND]
  EQUIVALENCE (predef_types(3), H5T_NATIVE_INTEGER_KIND(3))
--------------------------------^
H5f90global.F90(147): error #7615: Multiple objects from the same EQUIVALENCE
    set may not appear in a COMMON block.   [H5T_NATIVE_INTEGER_KIND]
  EQUIVALENCE (predef_types(4), H5T_NATIVE_INTEGER_KIND(4))
--------------------------------^
H5f90global.F90(148): error #7615: Multiple objects from the same EQUIVALENCE
    set may not appear in a COMMON block.   [H5T_NATIVE_INTEGER_KIND]
  EQUIVALENCE (predef_types(5), H5T_NATIVE_INTEGER_KIND(5))
--------------------------------^
compilation aborted for H5f90global.F90 (code 1)
make[3]: *** [H5f90global.lo] Error 1
```

@junghans This patch was tested on snow/grizzly with intel/18.0.1.

### CODE REVIEW

**Comment by adamjstewart** [comment]
@ssergien @robertsjohn might be interested in this.

**Comment by alalazo** [comment]
@KineticTheory Thanks!
