### ISSUE TITLE
sundials+pthread fails to build on Ubuntu16.04 + gcc 5.4.0

### ISSUE THREAD

**Issue by davydden** [spack/spack#5711]
```
[ 89%] Building C object examples/idas/serial/CMakeFiles/idasSlCrank_dns.dir/idasSlCrank_dns.c.o
cd /home/davydden/spack/var/spack/stage/sundials-2.7.0-cmwi46u5mqjo5gkh2bbbk6ogct66uzto/sundials-2.7.0/build/examples/idas/serial && /home/davydden/spack/lib/spack/env/gcc/gcc  -I/home/davydden/spack/var/spack/stage/sundials-2.7.0-cmwi46u5mqjo5gkh2bbbk6ogct66uzto/sundials-2.7.0/include -I/home/davydden/spack/var/spack/stage/sundials-2.7.0-cmwi46u5mqjo5gkh2bbbk6ogct66uzto/sundials-2.7.0/build/include  -fPIC -O2 -g -DNDEBUG   -o CMakeFiles/idasSlCrank_dns.dir/idasSlCrank_dns.c.o   -c /home/davydden/spack/var/spack/stage/sundials-2.7.0-cmwi46u5mqjo5gkh2bbbk6ogct66uzto/sundials-2.7.0/examples/idas/serial/idasSlCrank_dns.c
../../../src/nvec_pthreads/libsundials_nvecpthreads.so.2.7.0: undefined reference to `pthread_create'
../../../src/nvec_pthreads/libsundials_nvecpthreads.so.2.7.0: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
```

@gardner48 do you have any ideas?

**Comment by gardner48** [comment]
I'm guessing CMake is finding the `pthread` library but it is not getting included when linking (i.e., `-lpthread` is missing). During the cmake phase something like the following should have been output
```
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Pthreads
```
It's strange that this error occurs on this example problem (`idasSlCrank_dns`) which does not use the `pthread` vector.

**Comment by davydden** [comment]
unfortunately, I don't have the build folder at hand anymore (I can re-product next Monday), but `pthread` was found during CMakeConfig. So my best bet would be that during setting up this example in CMake, something is missing...

**Comment by gardner48** [comment]
I don't have this problem on Red Hat but I'll try this out on Ubuntu and try to reproduce the error.

**Comment by becker33** [comment]
Closing as unaddressed since ubuntu16 has been EOL for 3 years.
