### PR TITLE
Forbid the assignment of Repo and RepoPath super-namespace

### LINKED ISSUE #11159: Namespace arguments broken in spack.repo API
While coding towards #11158 I tried to use a custom namespace for the temporary repository being used. This caused strange errors, as for repositories that are not in the `spack.pkg` namespace directives won't be executed on their packages.

### Steps to reproduce the issue

```console
$ spack-python
Spack version 0.12.1
Python 2.7.15rc1, Linux x86_64
>>> import spack.repo
>>> import spack.spec
# Any repository path will be fine below
>>> repo = spack.repo.Repo('/tmp/tmp4yoo27fk', namespace='custom')
>>> spack.repo.path.put_first(repo)
# Choose a package in the custom repo
>>> s = spack.spec.Spec('concretizationroot')
>>> s.concretize()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1909, in concretize
    user_spec_deps=user_spec_deps),
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2322, in normalize
    self.validate_or_raise()
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 2374, in validate_or_raise
    spack.repo.get(spec.fullname)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 1198, in get
    return path.get(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 85, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 644, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 85, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 906, in get
    raise FailedConstructorError(spec.fullname, *sys.exc_info())
FailedConstructorError: Class constructor failed for package 'concretizationroot'.
    
Caused by:
AttributeError: 'Concretizationroot' object has no attribute 'versions'
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/repo.py", line 897, in get
    return package_class(spec)
  File "/home/mculpo/PycharmProjects/spack/lib/spack/spack/package.py", line 488, in __init__
    for v in self.versions:
```

### Additional information

This bug apparently was introduced in 39c9bbfbb which added this check:

https://github.com/spack/spack/blob/b2611c80862628046556c73e1e9da6ec69060428/lib/spack/spack/directives.py#L102-L104

to `DirectivesMeta`, which results in directives being executed only if the namespace of a repository is the default one. As a solution we could either relax this check, or simplify the repository interface by removing its optional `namespace` argument.

### PR DESCRIPTION
**Pull request by alalazo**
fixes #11159 

This PR forbids the assignment of custom super-namespaces for `Repo` and `RepoPath`, as the only super-namespace supported by package directives is `spack.pkg`. 

It also adds a few minor maintenance changes:
- [x] Using `functools.wrap` for the `autospec decorator
- [x] Remove unused arguments from `RepoPath.get`
- [x] Move directory cleanup in `create_repo` before raising (the code was unreachable before)

### CODE REVIEW

File: lib/spack/spack/repo.py [hunk 1]
```diff
@@ -448,7 +451,7 @@ def __init__(self, *repos, **kwargs):
         for repo in repos:
             try:
                 if isinstance(repo, string_types):
-                    repo = Repo(repo, self.super_namespace)
```
Comment (scheibelp) [inline lib/spack/spack/repo.py]: @alalazo so this all looks reasonable in that it should consider all package objects as part of the `spack.pkg` module, but the code before this also looks like it should do that. This is another way of saying that as I noted in https://github.com/spack/spack/issues/11159#issuecomment-484228264, I don't think the core problem has been identified.

That being said, if you added a unit test which checked for directives being applied to packages in alternative namespaces, and it passed here (and it fails for the current logic), then I think that would be sufficient reason for merging this. Let me know if you want to discuss how to do that.

Comment (alalazo) [reply lib/spack/spack/repo.py]: Summarizing a few things to check if my understanding of the code is correct. It seems to me that the `namespace` argument we can currently pass to `Repo` and `RepoPath` actually refers to the super-namespace i.e. usually `spack.pkg`, while the "real" namespace of the package is read from `repos.yaml` and usually coincides with the enclosing folder. 

To be less abstract the builtin repository is `spack.pkg.builtin` where `spack.pkg` is the super-namespace and `builtin` is the namespace. The intent of this PR is to prevent clients from being able to set the super-namespace at all, as that will create repositories with invalid packages due to the check in `directives.py`.

> That being said, if you added a unit test which checked for directives being applied to packages in alternative namespaces, and it passed here (and it fails for the current logic), then I think that would be sufficient reason for merging this. Let me know if you want to discuss how to do that.

I'm all in to add tests to this, but I think you're requiring the other fix I was mentioning in #11159 i.e. relaxing the constraint in `directives.py` and permit other super-namespaces. Am I getting this wrong?

Comment (scheibelp) [reply lib/spack/spack/repo.py]: > I'm all in to add tests to this, but I think you're requiring the other fix I was mentioning in #11159 i.e. relaxing the constraint in directives.py and permit other super-namespaces.

I don't think other super namespaces should be allowed (or should have to be supported). Maybe what I was getting confused by is that there are many changes and perhaps the only necessary changes are very small:

Now that I read through all of this again, it looks like the primary functional change is to remove the `namespace` argument from the `Repo` initializer; this prevents users from accidentally assigning a different super-namespace (which as you note in #11159 is not supported). So if that's true, then no test is needed because we are just removing functionality.

Also if that's true: please put the necessary change in a separate commit, or clarify in the PR description that this is the required change to address the issue.

Comment (alalazo) [reply lib/spack/spack/repo.py]: > Also if that's true: please put the necessary change in a separate commit, or clarify in the PR description that this is the required change to address the issue.

Sorry, the commits are well factored but it's true that the description was not useful at all. I changed that to reflect the changes better. The only necessary change to fix #11159 is 429b811 while the remaining three commits seemed to me easy and necessary changes to ease later maintenance. Let me know if something else is needed by my side.

**Comment by scheibelp** [comment]
Thanks!
