### ISSUE TITLE
Installation issue : faulty install py-pytest 

### ISSUE THREAD

**Issue by s-sajid-ali** [spack/spack#9037]
### Steps to reproduce the issue

```
$ spack install py-pytest ^python@2.7.14 %gcc@7.3.0
```

### Platform and user environment
```commandline
$ uname -a 
Linux xrmlite.phys.northwestern.edu 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.5.1804 (Core)
``` 
### Additional information
```
[sajid@xrmlite ~]$ spack spec --install-status py-pytest ^python@2.7.14 %gcc@7.3.0
Input spec
--------------------------------
     py-pytest
         ^python@2.7.14%gcc@7.3.0

Concretized
--------------------------------
[+]  py-pytest@3.7.1%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]      ^py-attrs@18.1.0%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]          ^py-setuptools@39.2.0%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]              ^python@2.7.14%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell" +dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-centos7-x86_64
[+]                  ^bzip2@1.0.6%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell" +shared arch=linux-centos7-x86_64
[+]                  ^gdbm@1.14.1%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]                      ^readline@7.0%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]                          ^ncurses@6.1%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell" ~symlinks~termlib arch=linux-centos7-x86_64
[+]                              ^pkgconf@1.4.2%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]                  ^openssl@1.0.2o%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell" +systemcerts arch=linux-centos7-x86_64
[+]                      ^zlib@1.2.11%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell" +optimize+pic+shared arch=linux-centos7-x86_64
[+]                  ^sqlite@3.23.1%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell" ~functions arch=linux-centos7-x86_64
[+]      ^py-funcsigs@0.4%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]      ^py-more-itertools@4.1.0%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]          ^py-six@1.11.0%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]      ^py-pluggy@0.6.0%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]      ^py-py@1.5.3%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
[+]      ^py-setuptools-scm@1.15.6%gcc@7.3.0 cflags="-march=haswell" cxxflags="-march=haswell"  arch=linux-centos7-x86_64
```
Spack installed a faulty software as shown by  : 
```
[sajid@xrmlite ~]$ spack load python@2.7.14%gcc@7.3.0
[sajid@xrmlite ~]$ python
Python 2.7.14 (default, Aug 19 2018, 00:55:00)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/python-2.7.14-qsmj5skc4e7rorg2ayxpkva4hhapwaw6/lib/python2.7/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/python-2.7.14-qsmj5skc4e7rorg2ayxpkva4hhapwaw6/lib/python2.7/site-packages/_pytest/config/__init__.py", line 18, in <module>
    import _pytest.hookspec  # the extension point definitions
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/python-2.7.14-qsmj5skc4e7rorg2ayxpkva4hhapwaw6/lib/python2.7/site-packages/_pytest/hookspec.py", line 27, in <module>
    @hookspec(historic=True, warn_on_impl=PYTEST_NAMESPACE)
TypeError: __call__() got an unexpected keyword argument 'warn_on_impl'
>>>
```

**Comment by healther** [comment]
unless you did something like `spack activate py-pytest`, you didn't make `py-pytest` available to `python`

**Comment by s-sajid-ali** [comment]
I did activate it. To confirm : 
```
[sajid@xrmlite ~]$ spack load python@2.7.14%gcc@7.3.0
[sajid@xrmlite ~]$ spack load py-pytest ^python@2.7.14%gcc@7.3.0
[sajid@xrmlite ~]$ python
Python 2.7.14 (default, Aug 19 2018, 00:55:00)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/py-pytest-3.7.1-wodlkwqrk3twmwafi47ukojcvdhogoer/lib/python2.7/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/py-pytest-3.7.1-wodlkwqrk3twmwafi47ukojcvdhogoer/lib/python2.7/site-packages/_pytest/config/__init__.py", line 18, in <module>
    import _pytest.hookspec  # the extension point definitions
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/py-pytest-3.7.1-wodlkwqrk3twmwafi47ukojcvdhogoer/lib/python2.7/site-packages/_pytest/hookspec.py", line 27, in <module>
    @hookspec(historic=True, warn_on_impl=PYTEST_NAMESPACE)
TypeError: __call__() got an unexpected keyword argument 'warn_on_impl'
>>>
```

In any case, if I didn't make it available, I would have gotten a module unavailable error.

**Comment by s-sajid-ali** [comment]
I did activate it in the first post, but here is a confirmation of the same : 
```
[sajid@xrmlite ~]$ spack load python@2.7.14%gcc@7.3.0
[sajid@xrmlite ~]$ spack activate py-pytest ^python@2.7.14%gcc@7.3.0
==> Package py-pytest/ggnadys is already activated.
[sajid@xrmlite ~]$ python
Python 2.7.14 (default, Aug 19 2018, 00:55:00)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/python-2.7.14-qsmj5skc4e7rorg2ayxpkva4hhapwaw6/lib/python2.7/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/python-2.7.14-qsmj5skc4e7rorg2ayxpkva4hhapwaw6/lib/python2.7/site-packages/_pytest/config/__init__.py", line 18, in <module>
    import _pytest.hookspec  # the extension point definitions
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/python-2.7.14-qsmj5skc4e7rorg2ayxpkva4hhapwaw6/lib/python2.7/site-packages/_pytest/hookspec.py", line 27, in <module>
    @hookspec(historic=True, warn_on_impl=PYTEST_NAMESPACE)
TypeError: __call__() got an unexpected keyword argument 'warn_on_impl'
>>>
```

**Comment by s-sajid-ali** [comment]
Everything works with `python@3.6.5`. (Maybe the containerization for `python@2.7.x` is wrong.)

**Comment by adamjstewart** [comment]
Pretty sure the problem is `pluggy`: https://github.com/pytest-dev/pytest/issues/3753

I'll try upgrading `pytest` and all of its dependencies.
