### PR TITLE
Adding openmpi version 4.0.0

### PR DESCRIPTION
**Pull request by jrood-nrel**
I just tested 4.0.0 to get the libmpi.so version and it seems to build and install fine.

### CODE REVIEW

**Comment by dorier** [comment]
Since this PR was merge, we have a CI build that fails on our software stack: HDF5 doesn't build anymore. We are getting this:
```
>> 3779    ../src/.libs/libhdf5.so: undefined reference to `MPI_Type_extent'
  >> 3780    ../src/.libs/libhdf5.so: undefined reference to `OMPI_C_MPI_NULL_C
             OPY_FN'
  >> 3781    collect2: error: ld returned 1 exit status
  >> 3782    make[1]: *** [testhdf5] Error 1
     3783    make[1]: Leaving directory `/tmp/ci/spack-stage/spack-stage-WMtrAv
             /hdf5-1.10.4/test'
  >> 3784    make: *** [all-recursive] Error 1
```
A problem with the latest OpenMPI? With HDF5? With Spack?

**Comment by ax3l** [comment]
@jrood-nrel which compiler did you test? I am getting reports from users that OpenMPI 4.0.0 does not build with GCC 5.5 and I also see compile issues with GCC/GFortran 4.9.

Shall we keep the `default` version on the last 3.* release until some point releases are out? Trying to file upstream issues on it...

**Comment by dorier** [comment]
It doesn't build with gcc 6.3.0 either. On another of my platforms (I haven't checked the gcc version for that one) it does build, but then when I'm trying to build HDF5 I get link errors.

**Comment by ax3l** [comment]
@dorier can you please report this [upstream as well](https://github.com/open-mpi/ompi/issues?utf8=%E2%9C%93&q=is%3Aissue+4.0.0)?

@adamjstewart @jrood-nrel what do you think, let us keep `default=True` on the last 3.X release for now?
