### ISSUE TITLE
Installation issue: trilinos

### ISSUE THREAD

**Issue by DarylGrunau** [spack/spack#15423]
### Spack version

```console
$ spack --version
0.14.0-105-d6b0cf7
```

### Steps to reproduce the issue

```console
$ spack install trilinos@12.12.1%gcc@7.4.0~adios2~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost build_type=RelWithDebInfo ~cgns~chaco~complex~debug~dtk+epetra+epetraext+exodus+explicit_template_instantiation~float+fortran~fortrilinos gotype=long +gtest+hdf5+hypre+ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos~mesquite+metis~minitensor+ml~muelu~mumps+nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~shards+shared~shylu~stk~suite-sparse~superlu+superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib+zoltan+zoltan2 arch=linux-centos7-sandybridge
.
.
.
 >> 5968    /tmp/spack/spack-stage/spack-stage-trilinos-12.12.1-jojooamnznfq5nv6eykybl5vo5zoe4w7/spack-src/packages/amesos2/src/Amesos2_Superludist.cpp:57:29: error: expected constructo
             r, destructor, or type conversion before '(' token
     5969       AMESOS2_SOLVER_EPETRA_INST(Superludist);
     5970                                 ^
  >> 5971    make[2]: *** [packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Superludist.cpp.o] Error 1
     5972    make[2]: *** Waiting for unfinished jobs....
```

`trilinos@12.14.1` fails to build in the same way; `trilinos@12.18.1` succeeds!

### Platform and user environment

```commandline
$ uname -a 
Linux lap-fey1.lanl.gov 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:    CentOS Linux release 7.7.1908 (Core)
```

### Additional information

Commit d6b0cf75ed79ace3154de11ff3ad24af4e69f773 is the genesis of this problem; backing off to the prior commit enables both `trilinos@12.12.1` and `trilinos@12.14.1` to build successfully.  @mathsen, @aprokop, would you be willing to have a look at supporting a few downrev versions?

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mathsen** [comment]
@DarylGrunau At the moment I'm in the "outback" with no option to access my workstation. I will look into this issue tomorrow.

**Comment by adamjstewart** [comment]
@keitat is also listed as a maintainer in case they have any ideas.

**Comment by keitat** [comment]
This could relate to whether or not Amesos2_ENABLE_Epetra is set.  Otherwise, I can only recommend using the latest Trilinos release.  Trilinos doesn’t (practically) support back-porting bug fixes (as in, people haven’t been doing that systematically for years).

**Comment by mathsen** [comment]
@keitat I completely agree when it comes to using the latest release. Nevertheless [pull request 15288](https://github.com/spack/spack/pull/15288) made older versions of trilinos fail to compile, that's why I'm not sure, if we should try to preserve the "old default settings" for older releases or not.
I tried to compile @12.14.1 without this commit and ran into the same issue as @DarylGrunau, with this pull request it builds fine (as well as Trilinos @12.18.1 and @master).

**Comment by keitat** [comment]
I would change the latest version because the latest version of Trilinos (Amesos2) adjusted to the new release of SuperLU_DIST.
