### ISSUE TITLE
unifyfs fails to build, unknown type 'MPI_Fint'

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#15292]
Package `unifyfs` fails to build on Ubuntu 18.04, x86_64 with Spack develop (e3b357ad87). The full spack-build-log is attached, but the error is shown below. I've tried with both `mpich` and `openmpi` -- same error either way.

Full build log: [unifyfs-build-out.txt](https://github.com/spack/spack/files/4276893/unifyfs-build-out.txt)

**Error:**
```
make[3]: Entering directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build/client/src'
  CC       libunifyfs_la-margo_client.lo
  CC       libunifyfs_la-unifyfs.lo
  CC       libunifyfs_la-unifyfs-dirops.lo
  CC       libunifyfs_la-unifyfs-fixed.lo
  CC       libunifyfs_la-unifyfs-stack.lo
  CC       libunifyfs_la-unifyfs-stdio.lo
  CC       libunifyfs_la-unifyfs-sysio.lo
  CC       libunifyfs_la-pmpi_wrappers.lo
In file included from /tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/client/src/pmpi_wrappers.c:15:0:
/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/client/src/pmpi_wrappers.h:21:16: error: unknown type name 'MPI_Fint'
 void mpi_init_(MPI_Fint* ierr);
                ^~~~~~~~
/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/client/src/pmpi_wrappers.h:26:20: error: unknown type name 'MPI_Fint'
 void mpi_finalize_(MPI_Fint* ierr);
                    ^~~~~~~~
Makefile:646: recipe for target 'libunifyfs_la-pmpi_wrappers.lo' failed
make[3]: *** [libunifyfs_la-pmpi_wrappers.lo] Error 1
make[3]: Leaving directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build/client/src'
Makefile:460: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build/client'
Makefile:490: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/walker/spack-stage/spack-stage-unifyfs-0.9.0-yqx3hsbr465azvv6lwnq7q5vp7r5st3p/spack-src/spack-build'
Makefile:400: recipe for target 'all' failed
make: *** [all] Error 2
```

@CamStan

**Comment by CamStan** [comment]
@eugeneswalker, this appears to be a bug with our `auto-mount` feature that is enabled by default. For now, try installing without it while we figure this out:
```
spack install unifyfs~auto-mount
```

I have opened a corresponding issue in UnifyFS to track this ([#467](https://github.com/LLNL/UnifyFS/issues/467)).

**Comment by CamStan** [comment]
@eugeneswalker, [#468](https://github.com/LLNL/UnifyFS/pull/468) in UnifyFS fixed this for the `dev` branch and #15292 should fix this when installing the default version of 0.9.0.

**Comment by alalazo** [comment]
Can you add a `conflict` statement in the package to prevent the use of `+automount` for the versions that are affected by the bug? I think that would be enough to close this issue since a patch has already been merged upstream. Feel free to ping me for a review of the PR once submitted.

**Comment by alalazo** [comment]
@CamStan Never mind my comment above. I see that you wrote #15292 in https://github.com/spack/spack/issues/15292#issuecomment-594279069 but possibly you meant #15315.

**Comment by CamStan** [comment]
@alalazo, yup, thank you. I corrected it in my comment.
