### ISSUE TITLE
libiconv 1.14 should conflict with newer compilers

### ISSUE THREAD

**Issue by amklinv** [spack/spack#6613]
@tgamblin 

### Expected Result

I expected libiconv 1.14 to work with gcc 5.3.0 and 6.2.0.

### Actual Result

The build failed and reported
```
../lib/.libs/libiconv.so: undefined reference to 'aliases2_lookup'
```
It worked with gcc 4.9.2.  According to the internet, the inline semantics in newer versions of gcc are causing this problem.  I have not tried libiconv 1.15 and do not know if this is an issue with that version as well.

### Steps to reproduce the issue

```console
spack install libiconv@1.14%gcc@5.3.0
spack install libiconv@1.14%gcc@6.2.0
```

**Comment by amklinv** [comment]
I just tried libiconv@1.15 with gcc@5.3.0, which installed successfully.
