### ISSUE TITLE
cmake 3.11.2 fails to build with Intel 2017.3 compiler

### ISSUE THREAD

**Issue by davydden** [spack/spack#8317]
`cmake@3.11.2` fails to build with `Intel@2017.3`.
Same with `3.11.0`, which works ok with `gcc@4.8.5`.

Same issues with `Intel@2017.5`

### Expected Result

`cmake` builds with Intel compiler.

### Actual Result

```
==> Installing cmake
==> Using cached archive: /home/woody/iwtm/iwtm108/spack/var/spack/cache/cmake/cmake-3.11.2.tar.gz
==> Staging archive: /home/woody/iwtm/iwtm108/spack/var/spack/stage/cmake-3.11.2-7nyjsjtwze3wgthccgqfxgyjnye3gyyt/cmake-3.11.2.tar.gz
==> Created stage in /home/woody/iwtm/iwtm108/spack/var/spack/stage/cmake-3.11.2-7nyjsjtwze3wgthccgqfxgyjnye3gyyt
==> No patches needed for cmake
==> Building cmake [Package]
==> Executing phase: 'bootstrap'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j40'

59 errors found in build log:
     1404        ^
     1405
     1406    /tmp/iwtm108/spack-stage/spack-stage-YXTUX3/cmake-3.11.2/Source/kwsys/ProcessUNIX.c(1726): warning #266: function "sigprocmask" declared implicitly
     1407        if (sigprocmask(SIG_BLOCK, &mask, &old_mask) < 0) {
     1408            ^
     1409
  >> 1410    /tmp/iwtm108/spack-stage/spack-stage-YXTUX3/cmake-3.11.2/Source/kwsys/ProcessUNIX.c(1726): error: identifier "SIG_BLOCK" is undefined
     1411        if (sigprocmask(SIG_BLOCK, &mask, &old_mask) < 0) {
     1412                        ^
     1413
     1414    /tmp/iwtm108/spack-stage/spack-stage-YXTUX3/cmake-3.11.2/Source/kwsys/ProcessUNIX.c(1745): warning #266: function "sigprocmask" declared implicitly
     1415          sigprocmask(SIG_SETMASK, &old_mask, 0);
     1416          ^
     1417
  >> 1418    /tmp/iwtm108/spack-stage/spack-stage-YXTUX3/cmake-3.11.2/Source/kwsys/ProcessUNIX.c(1745): error: identifier "SIG_SETMASK" is undefined
     1419          sigprocmask(SIG_SETMASK, &old_mask, 0);
     1420                      ^
     1421
     1422    /tmp/iwtm108/spack-stage/spack-stage-YXTUX3/cmake-3.11.2/Source/kwsys/ProcessUNIX.c(1787): warning #266: function "sigprocmask" declared implicitly
     1423          sigprocmask(SIG_SETMASK, &old_mask, 0);
     1424          ^
     1425
  >> 1426    /tmp/iwtm108/spack-stage/spack-stage-YXTUX3/cmake-3.11.2/Source/kwsys/ProcessUNIX.c(1787): error: identifier "SIG_SETMASK" is undefined
     1427          sigprocmask(SIG_SETMASK, &old_mask, 0);
     1428                      ^

<...and-more...>
```

`--dirty` does not help 😢 

### Steps to reproduce the issue

```console
$ spack install cmake
```

### Information on your system

centos7 x86_64 cluster

**Comment by adamjstewart** [comment]
@mathstuf

**Comment by davydden** [comment]
The only thing I could find online is [this post in Stackoverflow](https://stackoverflow.com/a/30284065/888478) where it is mentioned that one might need extra compiler flags. 
I also asked this question in [Intel forum](https://software.intel.com/en-us/forums/intel-c-compiler/topic/779719).

**Comment by skosukhin** [comment]
It's a problem with cmake. I described it in [the same thread](https://software.intel.com/en-us/forums/intel-c-compiler/topic/779719).
