### ISSUE TITLE
openmpi 3.0.0 linker error on Centos 7

### ISSUE THREAD

**Issue by sknigh** [spack/spack#5784]
``` bash
spack install openmpi@3.0.0%gcc@4.8.5~cuda fabrics=pmi ~java schedulers=slurm +sqlite3~thread_multiple+vt
...
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j56'
6 errors found in build log:
     [ ... ]
     7822    GENERATE mpi/man/man3/MPI_Win_unlock_all.3
     7823    GENERATE mpi/man/man3/MPI_Win_wait.3
     7824    GENERATE mpi/man/man3/MPI_Wtick.3
     7825    GENERATE mpi/man/man3/MPI_Wtime.3
     7826    GENERATE mpi/man/man3/OpenMPI.3
     7827    CCLD     libmpi.la
  >> 7828  /usr/bin/ld: cannot find -lbfd
  >> 7829  /usr/bin/ld: cannot find -liberty
  >> 7830  collect2: error: ld returned 1 exit status
  >> 7831  make[2]: *** [libmpi.la] Error 1
     7832  make[2]: Leaving directory `spack-stage/spack-stage-sgCto5/openmpi-3.0.0/ompi'
  >> 7833  make[1]: *** [all-recursive] Error 1
     7834  make[1]: Leaving directory `spack-stage/spack-stage-sgCto5/openmpi-3.0.0/ompi'
  >> 7835  make: *** [all-recursive] Error 1
```
This error did not occur with the same variants @1.10.3

**Comment by sknigh** [comment]
Made a little progress after finding binutils was missing from the image

``` bash
yum install -y binutils binutils-devel
```

Another error appears 800 lines later

``` bash
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j56'

5 errors found in build log:
     [ ... ]
     8632  Making all in tools/ompi_info
     8633  make[2]: Entering directory `/spack-stage/spack-stage-G3ybVj/openmpi-3.0.0/ompi/tools/ompi_info'
     8634    CC       param.o
     8635    CC       ompi_info.o
     8636    GENERATE ompi_info.1
     8637    CCLD     ompi_info
  >> 8638  ../../../ompi/.libs/libmpi.so: undefined reference to `ucp_request_free'
  >> 8639  collect2: error: ld returned 1 exit status
  >> 8640  make[2]: *** [ompi_info] Error 1
     8641  make[2]: Leaving directory `spack-stage/spack-stage-G3ybVj/openmpi-3.0.0/ompi/tools/ompi_info'
  >> 8642  make[1]: *** [all-recursive] Error 1
     8643  make[1]: Leaving directory `spack-stage/spack-stage-G3ybVj/openmpi-3.0.0/ompi
```

**Comment by JusticeForMikeBrown** [comment]
I was able to compile after adding ```binutils binutils-devel```

**Comment by JusticeForMikeBrown** [comment]
Never mind

Same error:

```
make[2]: Entering directory `/tmp/root/spack-stage/spack-stage-te9N8l/openmpi-3.0.0/ompi/tools/ompi_info'
  CC       ompi_info.o
  CC       param.o
  GENERATE ompi_info.1
  CCLD     ompi_info
../../../ompi/.libs/libmpi.so: undefined reference to `ucp_request_free'
```

**Comment by JusticeForMikeBrown** [comment]
Opened an issue on OpenMPI Github...

**Comment by JusticeForMikeBrown** [comment]
Was told to upgrade ucx version from 1.0 to 1.2.  

Mellanox RHEL 7.4 OFED has ucx 1.2.  Will upgrade server to 7.4 as well as OFED then try again!

**Comment by JusticeForMikeBrown** [comment]
ucx 1.2 fixed the problem

**Comment by sknigh** [comment]
I can confirm it builds on Centos 7.4. Thanks @JusticeForMikeBrown
