### PR TITLE
hdf5: add 1.10.2

### PR DESCRIPTION
**Pull request by dguibert**

### CODE REVIEW

**Comment by ax3l** [comment]
Am I the only one experiencing build issues with old MPI variants (e.g. OpenMPI 1.6.5) and parallel HDF5 1.10.2 of the form
```
H5Dmpio.c:3027:17: error: use of undeclared identifier 'MPI_Message'
     1064                    MPI_Message message;
```
? Worked in 1.10.1...

**Comment by ax3l** [comment]
Yep, turns out a requirement on [MPI-3](https://twitter.com/science_dot/status/1006644951151607808) slipped in...
