### ISSUE TITLE
Installation issue: `vtk@9.4`

### ISSUE THREAD

**Issue by Chrismarsh** [spack/spack#48738]
### Steps to reproduce the issue

```
$ spack install vtk@9.4
```
tested  with `apple-clang@16`

### Error message

There are a few problems with `vtk@9.4` (tested with macos `apple-clang@16`):
1. The newer seacas libraries require c++17
```
     7613    In file included from /Users/cbm038/Documents/science/code/spack/stage/spack-stage-vtk-9.4.1-cahuuqptngmacm3roxecdaiy5fxulldc/spack-src/IO/IOSS/vtkIOSSUtilities.h:33:
     7614    In file included from /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/seacas-2024-08-15-7j67v4dt7cmrgpe76v7outoj6phhbv7x/include/Ioss_Region.h:11:
     7615    In file included from /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/seacas-2024-08-15-7j67v4dt7cmrgpe76v7outoj6phhbv7x/include/Ioss_DatabaseIO.h:
             15:
     7616    In file included from /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/seacas-2024-08-15-7j67v4dt7cmrgpe76v7outoj6phhbv7x/include/Ioss_ParallelUtils
             .h:10:
     7617    In file included from /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/seacas-2024-08-15-7j67v4dt7cmrgpe76v7outoj6phhbv7x/include/Ioss_Utils.h:10:
     7618    In file included from /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/seacas-2024-08-15-7j67v4dt7cmrgpe76v7outoj6phhbv7x/include/Ioss_ElementTopolo
             gy.h:10:
  >> 7619    /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/seacas-2024-08-15-7j67v4dt7cmrgpe76v7outoj6phhbv7x/include/Ioss_ElementPermutation.h:32:82: error:
             too few template arguments for class template 'less'
     7620       32 |   using ElementPermutationMap = std::map<std::string, ElementPermutation *, std::less<>>;
     7621          |                                                                                  ^
     7622    /Library/Developer/CommandLineTools/SDKs/MacOSX15.2.sdk/usr/include/c++/v1/__functional/operations.h:355:29: note: template is declared here
     7623      353 | template <class _Tp>
     7624          | ~~~~~~~~~~~~~~~~~~~~
     7625      354 | #endif

```
2. int128 not correctly handled
```
 7695    In file included from /Users/cbm038/Documents/science/code/spack/stage/spack-stage-vtk-9.4.1-qbghoseun3fpch66u4uenmz2af5dg3fo/spack-src/IO/IOSS/vtkIOSSWriter.cxx:47:
  >> 7696    /Users/cbm038/Documents/science/code/spack/stage/spack-stage-vtk-9.4.1-qbghoseun3fpch66u4uenmz2af5dg3fo/spack-src/ThirdParty/fmt/vtkfmt/vtkfmt/core.h:596:19: error: unknown type name 'int1
             28_opt'; did you mean 'fmt::detail::int128_opt'?
     7697      596 | FMT_TYPE_CONSTANT(int128_opt, int128_type);
     7698          |                   ^
     7699    /Users/cbm038/Documents/science/code/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/fmt-11.1.2-zfff7er2yyernbsyzrun2ziix7idd2vu/include/fmt/base.h:406:7: note: 'fmt::detail::int128_op
             t' declared here
     7700      406 | using int128_opt = __int128_t;  // An optional native 128-bit integer.
     7701          |       ^
```
3. Incorrect types
```
  >> 7713    /Users/cbm038/Documents/science/code/spack/stage/spack-stage-vtk-9.4.1-tax5qujvgm5wh43camoo44y7ip7wd4z5/spack-src/IO/IOSS/vtkIOSSUtilities.cxx:304:25: error: use of undeclared identifier 'vtkioss_Ioss'
     7714      304 |   if (entity->type() == vtkioss_Ioss::NODEBLOCK &&
     7715          |                         ^
  >> 7716    /Users/cbm038/Documents/science/code/spack/stage/spack-stage-vtk-9.4.1-tax5qujvgm5wh43camoo44y7ip7wd4z5/spack-src/IO/IOSS/vtkIOSSUtilities.cxx:305:25: error: use of undeclared identifier 'vtkioss_Ioss'
     7717      305 |     field.get_role() == vtkioss_Ioss::Field::RoleType::TRANSIENT && // Nodal / Elem Variables
     7718          |                         ^
     7719    2 errors generated.
  >> 7720    make[2]: *** [IO/IOSS/CMakeFiles/IOIOSS.dir/build.make:163: IO/IOSS/CMakeFiles/IOIOSS.dir/vtkIOSSUtilities.cxx.o] Error 1
     7721    [ 68%] Building CXX object Filters/FlowPaths/CMakeFiles/FiltersFlowPaths.dir/vtkVortexCore.cxx.o
```

4. missing symbol
```
  >> 7816    Undefined symbols for architecture arm64:
     7817      "vtkfmt::v11::vformat(vtkfmt::v11::basic_string_view<char>, vtkfmt::v11::basic_format_args<vtkfmt::v11::basic_format_context<vtkfmt::v11::appender, char>>)", referenced from:
     7818          vtkIOSSWriter::WriteData() in vtkIOSSWriter.cxx.o
     7819    ld: symbol(s) not found for architecture arm64
```

### Information on your system

```
 spack debug report
* **Spack:** 0.24.0.dev0 (0afac0beaa1ab8ad42647742d0ee275704fb6b1e)
* **Python:** 3.12.6
* **Platform:** darwin-sonoma-m1
* 
```

### Additional information

@chuckatkins  @danlipsa  @johnwparent

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Chrismarsh** [comment]
I have fixes for the first 3 in https://github.com/spack/spack/pull/48739 but I cannot figure out what needs to be done to fix the missing symbol

**Comment by oeblo19** [comment]
Hi Chrismarsh, any update on this issue? Does it work with any prior version? I tried 9.3 without success.

**Comment by Chrismarsh** [comment]
I'm waiting to hear back from @johnwparent (who is at kitware) as they are implementing a fix in vtk. I'm not sure where they are with that.

VTK 9.2 consistently builds for me -- try that?

**Comment by Chrismarsh** [comment]
The new changes done to the vtk package have fixed all the problems but the missing symbol remains

**Comment by Chrismarsh** [comment]
@johnwparent still busted, although a new error I haven't seen before

```
undefined symbols for architecture arm64:
  "_glGetDoublev", referenced from:
      vtkOpenGLGL2PSHelperImpl::GetTransformParameters(vtkRenderer*, vtkMatrix4x4*, vtkMatrix4x4*, double*, double*, double*) in vtkOpenGLGL2PSHelperImpl.cxx.o
ld: symbol(s) not found for architecture arm64
```
