### ISSUE TITLE
Installation issue: fontconfig@2.12.3

### ISSUE THREAD

**Issue by pat-s** [spack/spack#10549]
### Steps to reproduce the issue

```console
$ spack install fontconfig # Fill in the exact spec you are using

==> pkgconf is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/pkgconf-1.5.4-dctgtaoctevv4r4moxeojpicihl3ulud
==> util-macros is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/util-macros-1.19.1-4smpt37rsocd54ufitlrzzampd6iyp5z
==> font-util is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/font-util-1.3.1-h55nsu23m7d42ti2wriootz76d5jfuds
==> diffutils is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/diffutils-3.7-lx777rqcelb6klntlvdotfxmdphv2a6n
==> bzip2 is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/bzip2-1.0.6-7djguhm2gowcvvtpweipynfjcj2szvxw
==> zlib is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/zlib-1.2.11-6wdekzyadff6repdb5bxinnzizvnn35t
==> libpng is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/libpng-1.6.34-nu6yixyycj7hxqfvjrgsgnwcj3tihijj
==> freetype is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/freetype-2.9.1-zxaa544tfem3hiqif4p3hysfnzhcxxrv
==> gperf is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/gperf-3.0.4-rggielmpgsffz6zp2b7zjdoe7v4fzc2v
==> libiconv is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/libiconv-1.15-q7w32zbfjms2zfzcllbtovtga4r46u6z
==> xz is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/xz-5.2.4-fvj6tohizvl45nmccwhd36ppjrtsxrte
==> libxml2 is already installed in /home/patrick/spack/opt/spack/linux-centos7-x86_64/gcc-8.2.0/libxml2-2.9.8-z2gjacsstfth7p2zx2t2jzdeyk2vmqbo
==> Installing fontconfig
==> Searching for binary cache of fontconfig
==> Warning: No Spack mirrors are currently configured
==> No binary for fontconfig found: installing from source
==> Using cached archive: /home/patrick/spack/var/spack/cache/fontconfig/fontconfig-2.12.3.tar.gz
==> Staging archive: /home/patrick/spack/var/spack/stage/fontconfig-2.12.3-k6alcznrzb7ljvp2l6x63fx6am5icreq/fontconfig-2.12.3.tar.gz
==> Created stage in /home/patrick/spack/var/spack/stage/fontconfig-2.12.3-k6alcznrzb7ljvp2l6x63fx6am5icreq
==> No patches needed for fontconfig
==> Building fontconfig [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
6 errors found in build log:
     292      CC       fcweight.lo
     293      CC       fcxml.lo
     294      CC       ftglue.lo
     295      CC       fcarch.o
     296      CCLD     fcarch
     297    In file included from fcobjs.c:33:
  >> 298    fcobjshash.gperf:28:1: error: conflicting types for 'FcObjectTypeHash'
     299     "aspect",FC_ASPECT_OBJECT
     300     ^~~~~~~~~~~~~~~~
     301    fcobjs.c:28:1: note: previous declaration of 'FcObjectTypeHash' was here
     302     FcObjectTypeHash (register const char *str, register FC_GPERF_SIZE_T len);
     303     ^~~~~~~~~~~~~~~~
     304    In file included from fcobjs.c:33:
  >> 305    fcobjshash.gperf:172:1: error: conflicting types for 'FcObjectTypeLookup'
     306    fcobjs.c:31:1: note: previous declaration of 'FcObjectTypeLookup' was here
     307     FcObjectTypeLookup (register const char *str, register FC_GPERF_SIZE_T len);
     308     ^~~~~~~~~~~~~~~~~~
  >> 309    make[3]: *** [fcobjs.lo] Error 1
     310    make[3]: *** Waiting for unfinished jobs....
     311    make[3]: Leaving directory `/tmp/patrick/spack-stage/spack-stage-F_0_1l/fontconfig-2.12.3/src'
  >> 312    make[2]: *** [all] Error 2
     313    make[2]: Leaving directory `/tmp/patrick/spack-stage/spack-stage-F_0_1l/fontconfig-2.12.3/src'
  >> 314    make[1]: *** [all-recursive] Error 1
     315    make[1]: Leaving directory `/tmp/patrick/spack-stage/spack-stage-F_0_1l/fontconfig-2.12.3'
  >> 316    make: *** [all] Error 2
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux giscience-cluster 4.20.7-1.el7.elrepo.x86_64 #1 SMP Wed Feb 6 13:17:46 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
CentOS 7.5
``` 

(works with gcc@4.8.5)

**Comment by weijianwen** [comment]
`spack install fontconfig %gcc@8.3.0` works in the latest Spack. Since this issue has been inactive for long, I am closing it. Feel free to reopen it if necessary.
