### PR TITLE
py-astor: specify py-setuptools versions as build fail with latest version

### LINKED ISSUE #13532: py-astor is not compatible with latest version of py-setuptools
It seems py-astor is not compatible with latest (v41.4.0) py-setuptools, hence yielding build error. However, it builds just fine with earlier versions of py-setuptools.

### Steps to reproduce the issue

```console
$ spack install py-astor
...
    specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
AttributeError: 'SpecifierSet' object has no attribute 'split'
==> Error: ProcessError: Command exited with status 1:
    '/mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-7.4.0/python-2.7.16-xpjw43slye3gpenkpif4lzajlfpsj2b2/bin/python2.7' '
-s' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /cache/sbulut/spack-stage/spack-stage-py-astor-0.8.0-4xsdi27ycyhhgeurnqui2f3e75yzjwqf/spack-build-out.txt
```
### Information on your system

- Centos7
- python@2.7.16

### PR DESCRIPTION
**Pull request by Sinan81**
Fixes #13532

### CODE REVIEW

File: var/spack/repos/builtin/packages/py-astor/package.py [hunk 1]
```diff
@@ -17,6 +17,6 @@ class PyAstor(PythonPackage):
     version('0.6', sha256='175ec395cde36aa0178c5a3120d03954c65d1ef4bb19ec4aa30e9d7a7cc426c4')
 
     depends_on('python@2.7:2.8,3.4:')
-    depends_on('py-setuptools', type='build')
+    depends_on('py-setuptools@:41.0.1', type='build')
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-astor/package.py]: Any idea exactly which version of setuptools breaks things? Also, can you add a comment pointing to: https://github.com/berkerpeksag/astor/issues/162. That way we'll know when it gets fixed.

Comment (Sinan81) [reply var/spack/repos/builtin/packages/py-astor/package.py]: py-astor doesn't build with py-setuptools@41.4.0

File: var/spack/repos/builtin/packages/py-astor/package.py [hunk 2]
```diff
@@ -17,6 +17,8 @@ class PyAstor(PythonPackage):
     version('0.6', sha256='175ec395cde36aa0178c5a3120d03954c65d1ef4bb19ec4aa30e9d7a7cc426c4')
 
     depends_on('python@2.7:2.8,3.4:')
-    depends_on('py-setuptools', type='build')
+    # Build fails with py-setuptools@41.4.0
+    # https://github.com/berkerpeksag/astor/issues/162
+    depends_on('py-setuptools@:41.0.1', type='build')
```
Comment (adamjstewart) [inline var/spack/repos/builtin/packages/py-astor/package.py]:
```suggestion
    depends_on('py-setuptools@:43', type='build')
```
In case you know it doesn't build with 43 either

Comment (Sinan81) [reply var/spack/repos/builtin/packages/py-astor/package.py]: Good to know. Since `depends_on('py-setuptools@:41.0.1'...` excludes both v41.4.0 and v43.x.x, I'will keep the commit as it is. Does that make sense?

Comment (adamjstewart) [reply var/spack/repos/builtin/packages/py-astor/package.py]: It might be overly strict, but it's likely a hack that we'll remove in the future anyway...
