### PR TITLE
Suite-sparse: provide patch to fix builts with clang@6.0.0.

### PR DESCRIPTION
**Pull request by KineticTheory**
+ I am unable to build `suite-sparse@5.2.0` with `clang@6.0.0`.  The build fails with the error:

```
     2397    [ 99%] Linking C executable wildtype_demo
     2398    make[4]: Leaving directory
  `/tmp/spack-stage/spack-stage-w0XYhK/SuiteSparse/GraphBLAS/build'
  >> 2399    libgraphblas.so.2.0.1: undefined reference to `__fpclassify'
  >> 2400    clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 2401    make[4]: *** [wildtype_demo] Error 1
```

+ This error appears because libgraphblas.so requires `-lm`, but that link dependency is not explicitly listed in `GraphBLAS\CMakeLists.txt.`
+ A patch file is provided to add this dependency.  The patch is only applied when the compiler is `%clang`.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Did you submit this patch upstream to the developers?

**Comment by KineticTheory** [comment]
@adamjstewart I don't know much about suite-sparse other than it is a dependency for Trilinos.  After you pointed me toward #7610 and #7612, I decided to try a gcc@4.8.5 build.  Indeed, suite-sparse@5.2.0 fails to compile with gcc@4.8.5 (even after I patched the CMakeLists.txt and removed the gcc version check).  This is due to GraphBLAS' use of C++11's `thread_local` feature.  Chatter on gcc.gnu.org indicates that this feature was broken in gcc-4.8.

According the source code for suite-sparse@5.2.0, the graphBLAS component requires these compiler versions:
* `gcc@4.9.0:`
* `intel@18.0.0:`
* `clang@3.3.0:`

**Comment by adamjstewart** [comment]
Yeah, I was going to add that in #7612 but people are already building `suite-sparse` with GCC 4.8 and I didn't want to stop them 😛
