### ISSUE TITLE
ldc fails to build

### ISSUE THREAD

**Issue by hartzell** [spack/spack#5822]
I'm trying to add sambamba to my regular builds.  It needs ldc, which failed, I believe that this is the first error:

```
/foo/users/hartzelg/tmp/foo/spack-cime/foo/lib/spack/env/gcc/g++   -DDMDV2 -DHAVE_SC_ARG_MAX -DIN_LLVM -DLDC_INSTALL_PREFIX=\"/foo/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-5.4.0/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb\" -DLDC_LLVM_VER=500 -DLLVM_INTRINSIC_TD_PATH=\"/foo/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-5.4.0/llvm-5.0.0-ctm2ddve3cpkacmf2dlxjtgqvuwvcowe/include\" -DOPAQUE_VTBLS -D__LITTLE_ENDIAN__ -I/foo/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src/. -I/foo/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src/dmd2 -I/foo/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/sta
ge/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src/dmd2/root -I/tmp/hartzelg/spack-stage/spack-stage-_O_Jcr/ldc-0.17.4-src/spack-build/dmd2 -I/foo/users/hartzelg/tmp/foo/spack-cime/foo/var
/spack/stage/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src -isystem /foo/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-5.4.0/llvm-5.0.0-ctm2ddve3cpkacmf2dlxjtgqvuwvcowe/include -isystem /foo/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-5.4.0/libconfig-1.5-4htedoslndbotow4ioh7qb47p5jeizv7/include  -O2 -g -DNDEBUG   -I/foo/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-5.4.0/llvm-5.0.0-ctm2ddve3cpkacmf2dlxjtgqvuwvcowe/include -std=c++11 -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti   -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-non-virtual-dtor -Wno-pedantic -DLDC_POSIX  -o CMakeFiles/LDCShared.dir/gen/dvalue.cpp.o -c /foo/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src/gen/dvalue.cppIn file included from /foo/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src/gen/cl_helpers.cpp:10:0:    

/foo/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src/./gen/cl_helpers.h:185:40: error: expected ‘;’ at end of member declaration         MultiSetter(bool invert, bool *p, ...) LLVM_END_WITH_NULL;                                                                                                                                                                                                         ^                                                                                                                                                                                     /foo/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-ol6ggfe6a3suc6snayqirqz2nzjas2qb/ldc-0.17.4-src/./gen/cl_helpers.h:185:42: error: ‘LLVM_END_WITH_NULL’ does not name a type         MultiSetter(bool invert, bool *p, ...) LLVM_END_WITH_NULL;                                                                                                                                                                                                           ^
```

I know that I built it successfully back when @alalazo was merging the ldc package, I suspect that was with the underlying system compilers (gcc@4.8.x).  Now I"m trying to build it with a spack-built gcc@5.4.0.

Spack has moved on since ldc merged, perhaps something has changed there too.

I'll keep digging

**Comment by hartzell** [comment]
I see the same thing when I build with gcc@4.8.5.

Here's a better cut-and-paste of the fatal error:

```
/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/lib/spack/env/gcc/g++   -DDMDV2 -DHAVE_SC_ARG_MAX -DIN_LLVM -DLDC_INSTALL_PREFIX=\"/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-4.8.5/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d\" -DLDC_LLVM_VER=500 -DLLVM_INTRINSIC_TD_PATH=\"/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-4.8.5/llvm-5.0.0-svtypnuv6eudrmliwzngnrrnhpaelvmv/include\" -DOPAQUE_VTBLS -D__LITTLE_ENDIAN__ -I/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src/. -I/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src/dmd2 -I/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src/dmd2/root -I/tmp/hartzelg/spack-stage/spack-stage-GiwBCe/ldc-0.17.4-src/spack-build/dmd2 -I/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src -isystem /sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-4.8.5/llvm-5.0.0-svtypnuv6eudrmliwzngnrrnhpaelvmv/include -isystem /sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-4.8.5/libconfig-1.5-i3fmzdszpzg5ckrjp5yor4vakxvrqrmv/include  -O2 -g -DNDEBUG   -I/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/opt/spack/linux-centos7-x86_64/gcc-4.8.5/llvm-5.0.0-svtypnuv6eudrmliwzngnrrnhpaelvmv/include -std=c++11 -fPIC -fvisibility-inlines-hidden -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti   -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-non-virtual-dtor -Wno-pedantic -DLDC_POSIX  -o CMakeFiles/LDCShared.dir/gen/dvalue.cpp.o -c /sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src/gen/dvalue.cpp
In file included from /sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src/gen/cl_helpers.cpp:10:0:
/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src/./gen/cl_helpers.h:185:40: error: expected ‘;’ at end of member declaration
   MultiSetter(bool invert, bool *p, ...) LLVM_END_WITH_NULL;
                                        ^
/sc1/groups/seqit/users/hartzelg/tmp/foo/spack-cime/foo/var/spack/stage/ldc-bootstrap-0.17.4-3u2hje7axv74acio3akbtp73sltkjb3d/ldc-0.17.4-src/./gen/cl_helpers.h:185:42: error: ‘LLVM_END_WITH_NULL’ does not name a type
   MultiSetter(bool invert, bool *p, ...) LLVM_END_WITH_NULL;
                                          ^
make[2]: *** [CMakeFiles/LDCShared.dir/gen/cl_helpers.cpp.o] Error 1
```

**Comment by alalazo** [comment]
I am wondering if the update to `llvm@5.0` has something to do with it.

**Comment by hartzell** [comment]
@alalazo -- I'll look into it.

Just connected the dots a bit more and it's actually the `ldc-bootstrap` build that's failing.

**Comment by hartzell** [comment]
`ldc-bootstrap^llvm@4.0.1` built successfully.

**Comment by hartzell** [comment]
`ldc^llvm@4.0.1` also builds successfully.

**Comment by hartzell** [comment]
Making `llvm@4.0.1` the preferred version in my `packages.yaml` file also builds successfully.

I don't have time (trying to get a release of our internal environment out the "door") to run down the issues with `llvm@5.0.0`.

I can live with the constraint in `packages.yaml` or I could add a constraint to the `ldc` and `ldc-bootstrap` packages.  Let me know if you'd like a PR for the latter.

**Comment by kljohann** [comment]
I think https://github.com/ldc-developers/ldc/releases/tag/v0.17.5 has been released to support LLVM 5.0. As it covers LLVM 3.5 - 5.0 it should be a drop-in replacement for the compiler used during the bootstrap step. (But I don't use LDC so maybe @hartzell could test/confirm this?)

**Comment by hartzell** [comment]
I can take a swing at that today unless @alalazo's already on top of it.

**Comment by alalazo** [comment]
#5842 solves the issue for me. It's in PR on a different topic, the only changes relevant here are the one on `ldc` and `ldc-bootstrap`.

**Comment by hartzell** [comment]
Yep, that looks like it would do the job.  I'll move on to the rest of the day.  **THANKS**.
